spring:
  redis:
    host: 192.168.0.107
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/meet_soul?characterEncoding=utf8&useSSL=false
    username: szx
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    #开启驼峰命名法
    configuration:
      map-underscore-to-camel-case: true
    mybatis-plus:
      # xml地址
      mapper-locations: classpath:mapper/*mapper.xml
      # 实体扫描，多个package用逗号或者分号分隔
      type-aliases-package: com.szx.meet.entity   #自己的实体类地址
      configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

logging:
  level:
    root: info
  file:
    path:

weChatMiniProgram:
  appID: wx706e9bb22242b29b
  appSecret: 7ed6a610ba70387a13b4aa079f0844e2