spring:
  redis:
    host: 192.168.0.107
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/meet_soul?characterEncoding=utf8&useSSL=false
    username: szx
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml

    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.szx.meet.entity
    #逻辑删除配置
    global-config:
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 8080

logging:
  level:
    root: info
  file:
    path:

weChatMiniProgram:
  appID: wx706e9bb22242b29b
  appSecret: 7ed6a610ba70387a13b4aa079f0844e2